-- Runs before Hibernate validate (embedded H2). Surrogate id + FKs + unique pairs on join tables.
CREATE TABLE plant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    latitude VARCHAR(255),
    longitude VARCHAR(255),
    status VARCHAR(255),
    capacity_pct DECIMAL(19, 2),
    total_lines INTEGER,
    lines_active INTEGER
);

CREATE TABLE supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    latitude VARCHAR(255),
    longitude VARCHAR(255),
    contract_status VARCHAR(255)
);

CREATE TABLE shipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_item VARCHAR(255),
    quantity DECIMAL(19, 2),
    ship_number VARCHAR(255),
    status VARCHAR(255),
    receive_date TIMESTAMP WITH TIME ZONE
);

CREATE TABLE plant_supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    CONSTRAINT uk_plant_supplier UNIQUE (plant_id, supplier_id),
    CONSTRAINT fk_plant_supplier_plant FOREIGN KEY (plant_id) REFERENCES plant (id) ON DELETE CASCADE,
    CONSTRAINT fk_plant_supplier_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE
);

CREATE TABLE supplier_shipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    shipment_id BIGINT NOT NULL,
    CONSTRAINT uk_supplier_shipment UNIQUE (supplier_id, shipment_id),
    CONSTRAINT fk_supplier_shipment_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE,
    CONSTRAINT fk_supplier_shipment_shipment FOREIGN KEY (shipment_id) REFERENCES shipment (id) ON DELETE CASCADE
);

CREATE TABLE plant_shipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT NOT NULL,
    shipment_id BIGINT NOT NULL,
    CONSTRAINT uk_plant_shipment UNIQUE (plant_id, shipment_id),
    CONSTRAINT fk_plant_shipment_plant FOREIGN KEY (plant_id) REFERENCES plant (id) ON DELETE CASCADE,
    CONSTRAINT fk_plant_shipment_shipment FOREIGN KEY (shipment_id) REFERENCES shipment (id) ON DELETE CASCADE
);
